module.exports = {
  projects: [
    '<rootDir>/apps/starter-app',
    '<rootDir>/apps/starter-api',
    '<rootDir>/apps/cruds-app',
    '<rootDir>/libs/app-shared',
    '<rootDir>/libs/shared/assets',
    '<rootDir>/libs/shared/styles',
    '<rootDir>/libs/shared/environments',
    '<rootDir>/libs/shared/data-access',
    '<rootDir>/libs/shared/core',
    '<rootDir>/libs/shared/interfaces',
    '<rootDir>/libs/api-core',
    '<rootDir>/libs/api-shared',
    '<rootDir>/libs/shared/app-core',
    '<rootDir>/libs/shared/app-store',
    '<rootDir>/libs/shared/api-core',
    '<rootDir>/libs/shared/api-shared',
    '<rootDir>/libs/shared/api-acl',
  ],
}
