export enum AUTH {
  MAIL_EXISTS = 'MSG_I18N_auth.MAIL_EXISTS',
  INVALID_CREDENTIALS = 'MSG_I18N_auth.INVALID_CREDENTIALS',
  NOT_FOUND = 'MSG_I18N_auth.NOT_FOUND',
  INVALID_CODE = 'MSG_I18N_auth.INVALID_CODE',
  EXPIRED_CODE = 'MSG_I18N_auth.EXPIRED_CODE'
}
