export enum EXCEPTION {
  APP_ERROR = 'MSG_I18N_exception.APP_ERROR',
  UNAUTHORIZED = 'MSG_I18N_exception.UNAUTHORIZED',
  NOT_FOUND = 'MSG_I18N_exception.NOT_FOUND',
  RESTRICT = 'MSG_I18N_exception.RESTRICT',
  DUPLICATED = 'MSG_I18N_exception.DUPLICATED',
  EXIST_DESCRIPTION = 'MSG_I18N_exception.EXIST_DESCRIPTION',
  EXIST_COLOR = 'MSG_I18N_exception.EXIST_COLOR',
  EXIST_ICON = 'MSG_I18N_exception.EXIST_ICON',
  INVALID_DELETE_IDS = 'MSG_I18N_exception.INVALID_DELETE_IDS'
}
