export enum FILTER_OPERATOR {
  EQUAL = '$eq',
  NOT_EQUALS = '$ne',
  GREATER_THAN = '$gt',
  LOWER_THAN = '$lt',
  GREATER_THAN_OR_EQUAL = '$gte',
  LOWER_THAN_OR_EQUAL = '$lte',
  STARTS_WITH = '$starts',
  ENDS_WITH = '$ends',
  CONTAINS = '$cont',
  NOT_CONTAINS = '$excl',
  IN = '$in',
  NOT_IN = '$notin',
  IS_NULL = '$isnull',
  NOT_NULL = '$notnull',
  BETWEEN = '$between',
  LOWER_EQUAL = '$eqL',
  LOWER_NOT_EQUAL = '$neL',
  STARTS_LIKE = '$startsL',
  ENDS_LIKE = '$endsL',
  LIKE = '$contL',
  NOT_LIKE = '$exclL',
  LOWER_IN = '$inL',
  LOWER_NOT_IN = '$notinL'
}
